name: sentinel
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  sentinel-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install Sentinel
        uses: bloominlabs/setup-hashicorp-releases@24ba535809adca0a710fd39db83eef75cc90af0e # v2.0.0
        with:
          package: sentinel
          version: ^0.18.11
      - name: Sentinel Format
        run: sentinel fmt -check=true $(find . -name "*.sentinel" -type f)
  sentinel-test:
    needs: sentinel-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install Sentinel
        uses: bloominlabs/setup-hashicorp-releases@24ba535809adca0a710fd39db83eef75cc90af0e # v2.0.0
        with:
          package: sentinel
          version: ^0.18.11
      - name: Sentinel Test
        run: sentinel test $(find . -name "*.sentinel" -type f ! -path "*/testdata/*")
